// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gibbs_mv_rpm_cpp
List gibbs_mv_rpm_cpp(NumericMatrix Y, int n_iter, int burn, int thin, double M0, NumericVector Mv, double a_alpha, double b_alpha, double m0, double s0_sq, double a0, double b0, double atau, double btau, int n_new, NumericVector y_test, bool independent, Nullable<IntegerVector> c0_init, Nullable<List> c_view_init, Nullable<List> gamma_init, Nullable<NumericVector> alpha_init, Nullable<Function> prior_pred_logdens_det_fn, bool do_prediction, int n_particles, int n_pred_sweeps, bool exact_prediction, bool marginalize_alpha_prediction);
RcppExport SEXP _drpm_gibbs_mv_rpm_cpp(SEXP YSEXP, SEXP n_iterSEXP, SEXP burnSEXP, SEXP thinSEXP, SEXP M0SEXP, SEXP MvSEXP, SEXP a_alphaSEXP, SEXP b_alphaSEXP, SEXP m0SEXP, SEXP s0_sqSEXP, SEXP a0SEXP, SEXP b0SEXP, SEXP atauSEXP, SEXP btauSEXP, SEXP n_newSEXP, SEXP y_testSEXP, SEXP independentSEXP, SEXP c0_initSEXP, SEXP c_view_initSEXP, SEXP gamma_initSEXP, SEXP alpha_initSEXP, SEXP prior_pred_logdens_det_fnSEXP, SEXP do_predictionSEXP, SEXP n_particlesSEXP, SEXP n_pred_sweepsSEXP, SEXP exact_predictionSEXP, SEXP marginalize_alpha_predictionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< double >::type M0(M0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Mv(MvSEXP);
    Rcpp::traits::input_parameter< double >::type a_alpha(a_alphaSEXP);
    Rcpp::traits::input_parameter< double >::type b_alpha(b_alphaSEXP);
    Rcpp::traits::input_parameter< double >::type m0(m0SEXP);
    Rcpp::traits::input_parameter< double >::type s0_sq(s0_sqSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< double >::type atau(atauSEXP);
    Rcpp::traits::input_parameter< double >::type btau(btauSEXP);
    Rcpp::traits::input_parameter< int >::type n_new(n_newSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_test(y_testSEXP);
    Rcpp::traits::input_parameter< bool >::type independent(independentSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type c0_init(c0_initSEXP);
    Rcpp::traits::input_parameter< Nullable<List> >::type c_view_init(c_view_initSEXP);
    Rcpp::traits::input_parameter< Nullable<List> >::type gamma_init(gamma_initSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type alpha_init(alpha_initSEXP);
    Rcpp::traits::input_parameter< Nullable<Function> >::type prior_pred_logdens_det_fn(prior_pred_logdens_det_fnSEXP);
    Rcpp::traits::input_parameter< bool >::type do_prediction(do_predictionSEXP);
    Rcpp::traits::input_parameter< int >::type n_particles(n_particlesSEXP);
    Rcpp::traits::input_parameter< int >::type n_pred_sweeps(n_pred_sweepsSEXP);
    Rcpp::traits::input_parameter< bool >::type exact_prediction(exact_predictionSEXP);
    Rcpp::traits::input_parameter< bool >::type marginalize_alpha_prediction(marginalize_alpha_predictionSEXP);
    rcpp_result_gen = Rcpp::wrap(gibbs_mv_rpm_cpp(Y, n_iter, burn, thin, M0, Mv, a_alpha, b_alpha, m0, s0_sq, a0, b0, atau, btau, n_new, y_test, independent, c0_init, c_view_init, gamma_init, alpha_init, prior_pred_logdens_det_fn, do_prediction, n_particles, n_pred_sweeps, exact_prediction, marginalize_alpha_prediction));
    return rcpp_result_gen;
END_RCPP
}

RcppExport void drpm_ar1_sppm(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *);
RcppExport void informed_ar1_sppm(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *);
RcppExport void LDDP(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *);
RcppExport void WDDP(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *);
RcppExport SEXP GIBBS(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP GIBBS_CRP(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_drpm_gibbs_mv_rpm_cpp", (DL_FUNC) &_drpm_gibbs_mv_rpm_cpp, 27},
    {"drpm_ar1_sppm",     (DL_FUNC) &drpm_ar1_sppm,     41},
    {"informed_ar1_sppm", (DL_FUNC) &informed_ar1_sppm, 44},
    {"LDDP",              (DL_FUNC) &LDDP,              26},
    {"WDDP",              (DL_FUNC) &WDDP,              19},
    {"GIBBS",     (DL_FUNC) &GIBBS,     12},
    {"GIBBS_CRP", (DL_FUNC) &GIBBS_CRP, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_drpm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
